---
# tasks file for ajgarlag.elasticsearch
- name: adding elasticsearch repository GPG key
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: adding elasticsearch repository
  apt_repository:
    repo: deb http://packages.elasticsearch.org/elasticsearch/{{ ajgarlag_elasticsearch_minor_version }}/debian stable main
    update_cache: yes

- name: checking if JAVA is installed
  command: java -version
  ignore_errors: yes
  register: java_check
  changed_when: no

- name: installing JAVA package
  apt:
    pkg: "{{ ajgarlag_elasticsearch_java_package }}"
    state: latest
  when: java_check != 0

- name: installing elasticsearch
  apt:
    pkg: elasticsearch
    state: latest

- name: configuring elasticsearch
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^\s*#?\s*{{ item.key }}\s*:'
    line: '{{ item.key }}: {{ item.value }}'
  with_dict: ajgarlag_elasticsearch_settings
  notify:
    - restart elasticsearch

- name: installing elasticsearch plugins
  command: /usr/share/elasticsearch/bin/plugin -install {{ item.value }}
  args:
        creates: /usr/share/elasticsearch/plugins/{{ item.key }}
  with_dict: ajgarlag_elasticsearch_plugins

- name: setting elasticsearch to autostart
  service:
    name: elasticsearch
    enabled: yes
  notify:
    - restart elasticsearch
